# Generated by Django 3.2.8 on 2021-10-18 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('license_duration', models.CharField(max_length=5)),
                ('device_count', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('alert_key_limit', models.CharField(max_length=20)),
                ('owner', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_partner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity for every user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_users', to='license_key_shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='license_key_shop.userextended')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user_extended',
            field=models.ManyToManyField(through='license_key_shop.UserProduct', to='license_key_shop.UserExtended'),
        ),
    ]
