# Generated by Django 3.2.8 on 2021-10-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='device_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='license_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='alert_key_limit',
            field=models.IntegerField(default=50),
        ),
    ]
