# Generated by Django 3.2.8 on 2021-10-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0002_auto_20211018_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='userextended',
            name='key_limit',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='userextended',
            name='user_status',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Partner', 'Partner'), ('Store', 'Store'), ('Seller', 'Seller')], default='Owner', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
