# Generated by Django 3.2.8 on 2021-10-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0003_auto_20211018_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='key_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
