# Generated by Django 3.2.8 on 2021-10-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0005_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
