# Generated by Django 3.2.8 on 2021-10-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0007_alter_userextended_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='license_key_shop.userextended'),
        ),
    ]
