# Generated by Django 3.2.8 on 2021-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0008_userextended_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='key_sold_count',
            field=models.IntegerField(default=0),
        ),
    ]
