# Generated by Django 3.2.8 on 2021-10-19 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0009_userextended_key_sold_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='key_sold_count',
        ),
        migrations.CreateModel(
            name='SoldDateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sold_date', to='license_key_shop.userextended')),
                ('key', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='license_key_shop.key')),
            ],
        ),
    ]
