# Generated by Django 3.2.8 on 2021-10-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0013_alter_solddatelist_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_parent', to='license_key_shop.userextended'),
        ),
    ]
