# Generated by Django 3.2.8 on 2021-10-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0014_alter_userextended_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solddatelist',
            name='key',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_key', to='license_key_shop.key'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_child', to='license_key_shop.userextended'),
        ),
    ]
