# Generated by Django 3.2.8 on 2021-10-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license_key_shop', '0018_auto_20211022_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='alert_key_limit',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='key_limit',
        ),
        migrations.CreateModel(
            name='UserExtendedSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('due_date', models.DateField()),
                ('key_limit', models.IntegerField(default=0)),
                ('daily_available_keys', models.IntegerField(default=0)),
                ('sold_min', models.IntegerField(default=0)),
                ('sold_min_due_date', models.DateField()),
                ('key_left', models.IntegerField(default=0)),
                ('user_extended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extended_specification', to='license_key_shop.userextended')),
            ],
        ),
    ]
